skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fairshare = "5hqL9x1dqFpLutMWZ6Q1QaqcXAZyZciviw8ConPKLZrh"

[programs.devnet]
fairshare = "5hqL9x1dqFpLutMWZ6Q1QaqcXAZyZciviw8ConPKLZrh"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
